# Configuration d'exemple pour le pipeline d'extraction immobilière

# Configuration Centris
centris:
  # Localisations disponibles
  locations:
    - "Montréal"
    - "Laval"
    - "Montérégie"
    - "Laurentides"
    - "Lanaudière"
    - "Estrie"
    - "Mauricie"
    - "Chaudière-Appalaches"

  # Types de propriétés disponibles
  property_types:
    - "SingleFamilyHome" # Maison unifamiliale
    - "Condo" # Condo
    - "Plex" # Plex
    - "ResidentialLot" # Terrain résidentiel

  # Plage de prix (en dollars canadiens)
  price_range:
    min: 100000
    max: 5000000

  # Paramètres de recherche
  search_params:
    max_pages: 50 # Nombre maximum de pages à parcourir
    delay_between_requests: 2 # Délai entre les requêtes (secondes)
    timeout: 30 # Timeout des requêtes (secondes)

# Configuration de la base de données MongoDB
database:
  server_url: "localhost:27017"
  connection_string: "mongodb://localhost:27017"
  database_name: "real_estate_analytics"
  username: null # Laissez null si pas d'authentification
  password: null # Laissez null si pas d'authentification
  auth_source: "admin"
  auth_mechanism: "SCRAM-SHA-256"

  # Noms des collections MongoDB
  properties_collection: "properties_2024" # Collection des propriétés
  summaries_collection: "summaries_2024" # Collection des résumés
  logs_collection: "extraction_logs_2024" # Collection des logs

  # Options de connexion
  max_pool_size: 100
  min_pool_size: 0
  max_idle_time_ms: 30000
  server_selection_timeout_ms: 5000
  connect_timeout_ms: 5000
  socket_timeout_ms: 5000

# Configuration des performances
performance:
  batch_size: 25 # Taille des lots de traitement
  max_concurrent_requests: 5 # Nombre maximum de requêtes simultanées
  max_retries: 3
  retry_delay: 5

# Configuration du logging
logging:
  level: "INFO" # Niveau de log (DEBUG, INFO, WARNING, ERROR)
  file: "logs/pipeline.log" # Fichier de log
  format: "json" # Format des logs (json, console)
  max_file_size: "10MB" # Taille maximale du fichier de log
  backup_count: 5 # Nombre de fichiers de sauvegarde
