# Configuration pour le pipeline d'extraction immobilière

# Configuration Centris
centris:
  # Localisations recherchées avec leurs IDs
  locations_searched:
    - type: "GeographicArea"
      value: "Montérégie"
      type_id: "RARA16"
    - type: "GeographicArea"
      value: "Laurentides"
      type_id: "RARA15"
    - type: "GeographicArea"
      value: "Lanaudière"
      type_id: "RARA14"
    - type: "GeographicArea"
      value: "Estrie"
      type_id: "RARA05"
    - type: "GeographicArea"
      value: "Mauricie"
      type_id: "RARA04"
    - type: "GeographicArea"
      value: "Chaudière-Appalaches"
      type_id: "RARA12"
    - type: "GeographicArea"
      value: "Montréal (Île)"
      type_id: "GSGS4621"
    - type: "GeographicArea"
      value: "Laval"
      type_id: "GSGS4622"
    - type: "CityDistrict"
      value: "Chambly"
      type_id: 730

  # Types de propriétés disponibles
  property_types:
    - "Plex"
    - "SingleFamilyHome"
    - "SellCondo"
    - "ResidentialLot"

  # Plage de prix (en dollars canadiens)
  sale_price_min: 0
  sale_price_max: 5000000

  # Force la mise à jour des propriétés existantes
  force_update: false

# Configuration de la base de données MongoDB
database:
  server_url: "localhost:27017"
  connection_string: "mongodb://localhost:27017"
  database_name: "real_estate_analytics"
  username: null # Laissez null si pas d'authentification
  password: null # Laissez null si pas d'authentification
  auth_source: "admin"
  auth_mechanism: "SCRAM-SHA-256"

  # Noms des collections MongoDB
  properties_collection: "properties_2024"
  summaries_collection: "summaries_2024"
  logs_collection: "extraction_logs_2024"

  # Options de connexion
  max_pool_size: 100
  min_pool_size: 0
  max_idle_time_ms: 30000
  server_selection_timeout_ms: 5000
  connect_timeout_ms: 5000
  socket_timeout_ms: 5000

# Configuration des performances
max_workers: 4
batch_size: 50
request_timeout: 30

# Configuration du logging
log_level: "INFO"
log_file: null
max_retries: 3
retry_delay: 5
