# Configuration pour le Test d'Extraction Saint-Hyacinthe Plex
# Cette configuration évite l'utilisation de la collection properties_2024

# Configuration Centris
centris:
  # Localisation spécifique à Saint-Hyacinthe
  locations_searched:
    - type: "CityDistrict"
      value: "Saint-Hyacinthe"
      type_id: 693

  # Types de propriétés à rechercher
  property_types:
    - "Plex"

  # Plage de prix pour Saint-Hyacinthe
  sale_price_min: 100000
  sale_price_max: 1000000

  # Force la mise à jour des propriétés existantes
  force_update: false

# Configuration de la base de données MongoDB
database:
  server_url: "localhost:27017"
  connection_string: "mongodb://localhost:27017"
  database_name: "real_estate_analytics"
  username: null
  password: null
  auth_source: "admin"
  auth_mechanism: "SCRAM-SHA-256"

  # Collections temporaires pour les tests (évite properties_2024)
  properties_collection: "saint_hyacinthe_plex_test_temp"
  summaries_collection: "saint_hyacinthe_summaries_test_temp"
  logs_collection: "saint_hyacinthe_logs_test_temp"

  # Options de connexion
  max_pool_size: 10
  min_pool_size: 0
  max_idle_time_ms: 30000
  server_selection_timeout_ms: 5000
  connect_timeout_ms: 5000
  socket_timeout_ms: 5000

# Configuration des performances pour le test
max_workers: 2
batch_size: 5
request_timeout: 60

# Configuration du logging
log_level: "DEBUG"
log_file: "logs/saint_hyacinthe_test.log"
max_retries: 3
retry_delay: 2

# Configuration spécifique au test
test_config:
  max_test_properties: 10
  max_test_pages: 3
  test_timeout: 300
  use_temporary_collections: true
  cleanup_after_test: false # Garder les données pour inspection
